name: 🐛 Bug Report
description: Report a problem
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear and concise description of the bug or issue.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you running?
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: reproduce-steps
    attributes:
      label: Steps to Reproduce
      description: Please tell us how we can reproduce the undesired behavior.
      placeholder: |
        1. Go to [...]
        2. Click on [...]
        3. See error in [...]
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, please provide screenshots depicting the problem.
  - type: textarea
    id: logs
    attributes:
      label: Console output
      description: Please copy and paste any relevant log output. (This will be automatically formatted into code, so no need for backticks.)
      render: shell
      placeholder: |
        1. press Fn + F12
        2. click on tab console
        3. see errors
        4. take screenshots
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Please provide any additional information that may be relevant or helpful.
